PALETTE = ["#648FFF", "#2ECC71", "#8069EC", "#EA822C", "#D143A4", "#F1C40F", "#34495E"]

RC_PARAMS = {
    "figure.figsize": (24, 16),
    "lines.linewidth": 8,
    "text.color": "#212121",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.labelsize": 72,
    "axes.labelpad": 12,
    "axes.labelcolor": "#212121",
    "axes.labelweight": 600,
    "axes.linewidth": 6,
    "axes.edgecolor": "#212121",
    "xtick.bottom": True,
    "ytick.left": True,
    "xtick.major.pad": 12,
    "ytick.major.pad": 12,
    "xtick.labelsize": 56,
    "ytick.labelsize": 56,
    "xtick.color": "#212121",
    "ytick.color": "#212121",
    "xtick.major.size": 24,
    "ytick.major.size": 24,
    "xtick.major.width": 6,
    "ytick.major.width": 6,
    "xtick.minor.size": 12,
    "ytick.minor.size": 12,
    "xtick.minor.width": 2,
    "ytick.minor.width": 2,
    "legend.fontsize": 48,
    "legend.handletextpad": 0.4,
    "legend.labelspacing": 0.2,
    "legend.handlelength": 1,
    "grid.linewidth": 1,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.0,
}
